### PR TITLE
GesturePod reorg

### PR DESCRIPTION
**Pull request by SachinG007**
1) Merged EdgeML/Application/GesturePod/training into EdgeML/applications
2) Fixed broken references

### CODE REVIEW

**Comment by SachinG007** [comment]
@ShishirPatil  can you please check this PR once.

**Comment by ShishirPatil** [comment]
1. `cite` on `EdgeML/tree/master/applications/GesturePod` is broken. Link it to `https://dl.acm.org/doi/10.1145/3332165.3347881`.

2. a) Change `cd EdgeML/Applications/GesturePod/onComputer` to `cd EdgeML/applications/GesturePod/onComputer` to reflect re-org at `EdgeML/tree/master/applications/GesturePod/onComputer#quick-start`.
b) Similarly at `cd Applications/GesturePod/onMKR1000`.
c) Similarly at `EdgeML/tree/master/applications/GesturePod/training#data-collection`



________________________________

**Comment by SachinG007** [comment]
@ShishirPatil  resolved the comments

**Comment by ShishirPatil** [comment]
Looks good to me.

**Comment by SachinG007** [comment]
Looks good to merge then 
@harsha-simhadri

**Review by harsha-simhadri — APPROVED** [review]

**Pull request merged**
