### PR TITLE
Stitched-Up RNNPool Face Detection Model and Quantization Code Performance Refactor

### PR DESCRIPTION
**Pull request by ShikharJ**
There's a lot to be done here:

- [x] Additional utility functions and refactoring some existing activation functions such as `TanH`, `ReLU6` and `Sigmoid`
- [x] Adding support for variable demotion and usage of 8-bit and 16-bit quantized mixed operations
- [x] Implementing full pipeline as a model
- [x] Implementing quantized and floating-point numerical test-cases for the full pipeline
- [x] Adding the stripped down pipeline as a model
- [x] Adding complete documentation
- [x] Porting runtime-optimized code
- [x] Rewrite tests for runtime-optimized code and remove deprecated operators

### CODE REVIEW

**Comment by ShikharJ** [comment]
@harsha-simhadri This is ready for reviewing.

**Comment by harsha-simhadri** [comment]
@ShikharJ  Is there a way to move the model params to a place outside github. I am concerned about bloat in the repo. How large are all the model files you are planning to check in?

**Comment by ShikharJ** [comment]
@harsha-simhadri The collective size of the model params is around 2.2 MBs (1.6 MBs for the larger model and 0.6 MBs for the smaller model). I'm not aware if a modular method exists, apart from not committing the weight files into the master.

**Comment by harsha-simhadri** [comment]
@ShikharJ   I am able to checkout git lfs and compile, but unclear what are the exec files and their commandline args. can you please add some notes to README, and print out a help line when the execs are run?

**Review by harsha-simhadri — APPROVED** [review]

**Pull request merged**
