### PR TITLE
Model training for GesturePod

### PR DESCRIPTION
**Pull request by ShishirPatil**
Data Collection, Labelling, and Feature extraction for training a model for GesturePod

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@ShishirPatil @metastableB  Are we waiting for reviews or testing on this PR?

**Comment by metastableB** [comment]
@harsha-simhadri  Sorry, this is pending work I have to finish. You don't have any action items on this.

**Comment by ShishirPatil** [comment]
I think this is good to be merged into master.

**Comment by harsha-simhadri** [comment]
> I think this is now good to be merged into master.

@ShishirPatil  @metastableB  Has anyone been able to follow these instructions from scratch in a reasonable amount of time without additional help?

**Comment by SachinG007** [comment]
Step 4 in the readme requires the labelled csv files in a certain directory structure. The output of step 3 doesn't follow a similar directory structure as required by /scripts/s25_discrete_extraction_of_consolidated_festures.py

**Comment by ShishirPatil** [comment]
Hi Sachin, 
There is no s25_* in this repo. Can you please verify you are in the right repo.
Thanks

**Comment by ShishirPatil** [comment]
> 
> 
> > I think this is now good to be merged into master.
> 
> @ShishirPatil @metastableB Has anyone been able to follow these instructions from scratch in a reasonable amount of time without additional help?

> @harsha-simhadri I am able to follow the readme now.

@harsha-simhadri Ready to merge to master.

 Thanks, Shishir

**Pull request merged**
